authors:
  Burhan-Q:
    name: Burhan Qaddoumi
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/62214284
    url: https://github.com/Burhan-Q

# reference: https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.authors_file