name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    #   - uses: actions/setup-python@v5
    #     with:
    #       python-version: 3.x
      - uses: astral-sh/setup-uv@v5
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - run: uv venv .venv --python 3.11 && source .venv/bin/activate && uv pip install -U .
      - run: source .venv/bin/activate && mkdocs build
      
      # Inject meta tag into every HTML file
      - name: Inject Google verification meta tag
        run: |
          source .venv/bin/activate
          python inject_meta.py
      
      # - run: source .venv/bin/activate && uv sync --active && mkdocs gh-deploy --force
      #- run: source .venv/bin/activate && uv pip install -U . && mkdocs gh-deploy --force
      - run: source .venv/bin/activate && mkdocs gh-deploy --force --no-build --verbose
